# Generated by Django 2.0.5 on 2018-05-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relreq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourcepath', models.CharField(max_length=30)),
                ('resourcename', models.CharField(max_length=200)),
            ],
        ),
    ]
