# Generated by Django 2.0.5 on 2018-06-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relreq', '0003_dictgroup_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondictionaryentry',
            name='displayname',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jsondictionaryentry',
            name='displayvalue',
            field=models.BooleanField(default=True),
        ),
    ]
