# Generated by Django 2.0.5 on 2018-06-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relreq', '0004_auto_20180604_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondictionaryentry',
            name='displayname',
        ),
        migrations.AddField(
            model_name='jsondictionaryentry',
            name='hide_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jsondictionaryentry',
            name='hide_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jsondictionaryentry',
            name='displayvalue',
            field=models.CharField(max_length=40),
        ),
    ]
