# Generated by Django 2.0.5 on 2018-06-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relreq', '0005_auto_20180604_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictgroup',
            name='displayvalue',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='jsondictionaryentry',
            name='jsonvalue',
            field=models.CharField(max_length=40),
        ),
    ]
