# Generated by Django 2.0.5 on 2018-06-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relreq', '0006_auto_20180604_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='dictgroup',
            name='displayvalue',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
