# Generated by Django 2.0.5 on 2018-06-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relreq', '0007_auto_20180605_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
            ],
        ),
    ]
