# Generated by Django 2.0.5 on 2018-06-05 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relreq', '0009_auto_20180605_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondictionaryentry',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relreq.JsonDictionaryEntry'),
        ),
    ]
